package com.pragma.plazoleta.domain.exception;

public enum ErrorCode {
    INVALID_DISH,
    INVALID_RESTAURANT,
    INVALID_EMPLOYEE,
    DATA_NOT_FOUND,
    FORBIDDEN,
    UNAUTHORIZED,
    INVALID_PAGINATION,
    INVALID_ORDER_STATE,
    INVALID_STATUS,
    EXTERNAL_SERVICE_ERROR,
    ORDER_ALREADY_EXISTS,
    INVALID_CODE
}
